services:
  backend:
    build: Backend
    ports:
      - "5000:5000"
    image: debasishray/predictor-backend:v1.0
  
  # depends_on must be placed at last beacuse it depends upon backend.
  frontend:
    build: Frontend
    ports:
      - "3000:3000"
    image: debasishray/predictor-frontend:v1.0
    depends_on:
      - backend
